title: Sahil Sharma
email: sahil.sharma@inserm.fr
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Sahil Sharma,
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sahil.sharma.com" # the base hostname & protocol for your site
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build settings
plugins:
  - jekyll-feed
remote_theme: "mmistakes/minimal-mistakes"
title: Sahil Sharma
name: Sahil Sharma
description: Ultrasound Researcher

layout: single 

